function [] = FinalProject()
%for this to work you need to plot the function first, then you can label
%the graph, and then put in the UI control section. 
    title_name=input('Title? ', 's')  
    title(title_name);
    xTitle = uicontrol('style','Edit',...%Empty box for x title
                       'string','',...
                       'Units','normalized',...     
                       'Position',[.45 .1 .1 .05],...
                       'backgroundcolor','w',...
                      'Tag','EditField'); 
   yTitle = uicontrol('style','Edit',...%Empty box for y title
                       'string','',...
                       'Units','normalized',...     
                       'Position',[.035 .25 .1 .05],...
                       'backgroundcolor','w',...
                      'Tag','EditField'); 
   xInputs = uicontrol('style','Edit',... %box to input x values
                       'string','1',...
                       'Units','normalized',...     
                       'Position',[.1 .025 .1 .05],...
                       'backgroundcolor','w',...
                      'Tag','EditField'); 
                  
yInputs = uicontrol('style','Edit',... %box to input y values
                       'string','1',...
                       'Units','normalized',...     
                       'Position',[.85 .025 .1 .05],...
                       'backgroundcolor','w',...
                      'Tag','EditField'); 
   
      
    
function selection(src,event)
    val = c.Value;
    str = c.String;
    str{val};
    disp(['Selection: ' str{val}]);

    
end
end


